### ISSUE TITLE
update lodash version

### ISSUE THREAD

**Issue by troygoode** [bwestergard/node-postgres-named#12]
Because of the recent changes to npm, npm will attempt to keep dependencies as flat as possible. In one of my projects when I run `npm install` I now get a message like:

```bash
[504] {master} ~/dev/example $ npm install
npm WARN unmet dependency /Users/troy/dev/example/node_modules/node-postgres-named requires lodash@'~2.3.0' but will load
npm WARN unmet dependency /Users/troy/dev/example/node_modules/lodash,
npm WARN unmet dependency which is version 3.10.1
```

Can we get the version of lodash used bumped to the latest major release (`3`) and start using `^` instead of `~` for matching? Happy to submit a PR if desired.

**Comment by apechimp** [comment]
Consider using [greenkeeper](http://greenkeeper.io/) to have these PRs submitted automatically.
