### ISSUE TITLE
pg pool integration

### ISSUE THREAD

**Issue by jars** [bwestergard/node-postgres-named#36]
awesome package.

Quick question about integration with `pg-pool`... This definitely returned results into `results.rows`, but I want to make sure there are no caveats if I adopt this method.

```javascript
const PgPool  = require('pg-pool');
const PgNamed = require('node-postgres-named');
const config  = {...}

var pool = PgPool(config);

PgNamed.patch(pool);

pool.query('SELECT * FROM users WHERE email = $email AND active = $active;', { email: 'foo@bar.com', active: 1 }, (err, results) => {

  console.log(results.rows);

});
``` 

Any thoughts?

**Comment by vroudge** [comment]
Curious about this @jordanarseno any feedback?

**Comment by jars** [comment]
@vroudge It has worked fine for me since without noticable caveats, but I cannot say with confidence there aren't any. By the way @vroudge, I ES6-ified this repo if that interests you @ https://github.com/jordanarseno/node-postgres-named

**Comment by vroudge** [comment]
Already got the ES6 part handled myself 👍 

Alright, in prod straight away. Thanks!
